# Load ~/.extra, ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
# ~/.extra can be used for settings you don’t want to commit
for file in ~/dotfiles/.{extra,bash_prompt,exports,aliases,functions}; do
        [ -r "$file" ] && source "$file"
done
unset file

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME='muse'

# Set to this to use case-sensitive completion
CASE_SENSITIVE='false'

TITLE='true'

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS='true'

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn)

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
# Source zsh
source $ZSH/oh-my-zsh.sh

# Setup Paths
PATH=/bin
PATH=/sbin:$PATH
PATH=/usr/bin:$PATH
PATH=/usr/sbin:$PATH
PATH=/usr/local/bin:$PATH

# 3rd party tools
PATH=$PATH:/Users/161751/scripts/aws/eb/macosx/python2.7

# Include RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"